language: python
matrix:
  include:
    - name: "Python 2.7 on Linux"
      os: linux
      python: 2.7
    - name: "Python 3.4 on Linux"
      os: linux
      python: 3.4
    - name: "Python 3.5 on Linux"
      os: linux
      python: 3.5
    - name: "Python 3.6 on Linux"
      os: linux
      python: 3.6
    - name: "Python 2.7 on Windows"
      os: windows
      language: shell
      python: 2.7
      before_install:
        - choco install python --version 2.7.11 --params "PrependPath=1"
        - python -m pip install --upgrade pip six enum34
      env: PATH=/c/tools/python:/c/tools/python/Scripts:$PATH
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      python: 3.6
      before_install:
        - choco install python --version 3.6.8 --params "PrependPath=1"
        - python -m pip install --upgrade pip six
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install enum34; fi
script:
  - bash ./runtests.sh
